/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bezyapps_ndkdemo_MyActivity */

#ifndef _Included_com_bezyapps_ndkdemo_MyActivity
#define _Included_com_bezyapps_ndkdemo_MyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bezyapps_ndkdemo_MyActivity
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bezyapps_ndkdemo_MyActivity_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_bezyapps_ndkdemo_MyActivity
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bezyapps_ndkdemo_MyActivity_test
  (JNIEnv *, jobject);

/*
 * Class:     com_bezyapps_ndkdemo_MyActivity
 * Method:    image
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bezyapps_ndkdemo_MyActivity_image
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
